### ISSUE TITLE
Failed to install - Missing dependencies from requirements

### ISSUE THREAD

**Issue by namachieli** [StackStorm-Exchange/stackstorm-email#15]
Ran into an issue when trying to install the pack email v1.0.3 on a fresh install.

https://gist.github.com/namachieli/d5c9b96806c3c8451b362471901956b4

appears that gcc is a requirement that is missing from requirements.

After manually installing `apt-get install gcc` the email pack installed just fine.

**Comment by LindsayHill** [comment]
Can you update the README to note this?
