### ISSUE TITLE
Query: Is there any limit on how many number of IMAP sensors that can be added?

### ISSUE THREAD

**Issue by transhapHigsn** [StackStorm-Exchange/stackstorm-email#42]

**Comment by blag** [comment]
Digging through the code though, only one IMAP sensor will be created, but [every time it polls](https://github.com/StackStorm-Exchange/stackstorm-email/blob/7adc84c1fd374f27c4d59ae2d2225193df92d2ae/sensors/imap_sensor.py#L45) it [loops through all IMAP accounts](https://github.com/StackStorm-Exchange/stackstorm-email/blob/7adc84c1fd374f27c4d59ae2d2225193df92d2ae/sensors/imap_sensor.py#L78), [establishes a connection to the server for each account](https://github.com/StackStorm-Exchange/stackstorm-email/blob/7adc84c1fd374f27c4d59ae2d2225193df92d2ae/sensors/imap_sensor.py#L100), [grabs all unseen messages](https://github.com/StackStorm-Exchange/stackstorm-email/blob/7adc84c1fd374f27c4d59ae2d2225193df92d2ae/sensors/imap_sensor.py#L123), and [processes them](https://github.com/StackStorm-Exchange/stackstorm-email/blob/7adc84c1fd374f27c4d59ae2d2225193df92d2ae/sensors/imap_sensor.py#L127) by [mangling some data](https://github.com/StackStorm-Exchange/stackstorm-email/blob/7adc84c1fd374f27c4d59ae2d2225193df92d2ae/sensors/imap_sensor.py#L131) and [dispatching a trigger instance](https://github.com/StackStorm-Exchange/stackstorm-email/blob/7adc84c1fd374f27c4d59ae2d2225193df92d2ae/sensors/imap_sensor.py#L167).

So, the full answer to your question is: only one sensor will ever be created, but there is no hard limit to the number of IMAP accounts that are monitored.

**Comment by transhapHigsn** [comment]
Thanks @blag
