### ISSUE TITLE
error using email pack

### ISSUE THREAD

**Issue by PLPRASU** [StackStorm-Exchange/stackstorm-email#49]
st2 run email.send_email account=stackstorm email_to=to@gmail.com message="Hi there, wow!" email_from="from@gmail.com" subject="Intros"
i got this error like this
File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 395, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python3.8/site-packages/python_runner/python_action_wrapper.py", line 214, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/email/actions/send_email.py", line 59, in run
    s.login(account_data.get('username', str()), account_data.get('password', str()))
  File "/usr/lib/python3.8/smtplib.py", line 743, in login
    raise last_exception
  File "/usr/lib/python3.8/smtplib.py", line 732, in login
    (code, resp) = self.auth(
  File "/usr/lib/python3.8/smtplib.py", line 655, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbv\
5.7.14 9VEfhlylEByBXGAqVwSyxBJ1WFcpz8lGrGIzov2bZcuQiMArel13g6sSBd0KaTfcIPMmS\
5.7.14 2q7WUuWdbk6TmyLJsweItCJYwKEMvW8dFaTJUVbfn8vA4klqOc5KtiE_z_5xzoR_>\
5.7.14 Please log in via your web browser and then try again.\
5.7.14  Learn more at\
5.7.14  https://support.google.com/mail/answer/78754 z39-20020a05620a262700b0069fc13ce237sm9766129qko.104 - gsmtp')

**Comment by nzlosh** [comment]
This is a Google error, follow their link and read what's required to fix your google settings to permit the st2 email pack to authenticate with Google.  You might also want to read the README in this repository that gives the basic instructions to get it working with Gmail.

**Comment by PLPRASU** [comment]
i follow those steps but i am not saw the st2 email pack to authenticate with Google.

**Comment by nzlosh** [comment]
According to the documentation, if you've created the application specific password and correctly filled in the email pack configuration, authentication should work.  I don't use GMail so won't be able to provide any further assistance.
